site_name: nedoROS
nav:
  - О проекте: index.md
  - Аппаратная часть:
    - Обзор робота: hardware/overview.md
    - Инструкции и документация: hardware/assembly.md
    - Электроника: hardware/electronic.md
  - Программная часть:
    - Обзор системы управления: software/overview.md
    - Код низкого уровня: software/low_level.md
    - Код навигации и принятия решений: software/rpi_level.md
    - Видеозрение и классификация уточек: software/nav_level.md
  - Использование:
    - Запуск робота: usage/usage.md
  - MISC:
    - Сценарий видео: script/script.md
theme: readthedocs
